config/routes.rb
Rails.application.routes.draw do
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :employees
  resources :attendances, only:[:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :employee
  validates :employee_id, presence: true
  validates :point, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :employee_id, presence: true, uniqueness: true
  validates :name, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 4 }, allow_nil: true
  has_many :attendances, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private
  # ログインしているか確認
  def logged_in_employee
    unless logged_in?
      flash[:danger] = 'ログインが必要です'
      redirect_to login_url
    end
  end

  # 管理者ユーザーか確認
  def admin_employee
    unless current_employee.admin?
      flash[:danger] = 'このページは管理者のみが閲覧できます'
      redirect_to(login_url)
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :logged_in_employee, only: %i[index new create destroy]
  before_action :admin_employee, only: %i[index new create destroy]
  MAX_DISPLAY_ATTENDANCE = 10

  def index
    @attendances = Attendance.includes(:employee).order('created_at DESC').page(params[:page]).per(MAX_DISPLAY_ATTENDANCE)
  end

  def new
    @attendance = Attendance.new
  end

  def create
    @attendance = Attendance.new(attendance_params)
    if @attendance.save
      flash[:success] = 'チェック結果が保存されました'
      redirect_to '/attendances'
    else
      render 'new'
    end
  end

  def destroy; end

  private

  def attendance_params
    params.require(:attendance).permit(:employee_id, :ride_at, :ride_in,
                                       :attr_one, :attr_two, :attr_three, :attr_four, :attr_five,
                                       :attr_six, :attr_seven, :attr_eight, :attr_nine, :attr_ten,
                                       :memo, :point)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :logged_in_employee, only: %i[index show new create edit update destroy]
  before_action :admin_employee, only: %i[destroy]
  MAX_DISPLAY_EMPLOYEE = 10
  MAX_DISPLAY_ATTENDANCE = 13

  def index
    if params[:name].present?
      @employees = Employee.where('name=?', params[:name]).page(params[:page])
      flash.now[:success] = '１件の検索結果' if @employees.present?
    else
      @employees = Employee.page(params[:page]).per(MAX_DISPLAY_EMPLOYEE)
    end
  end

  def show
    @employee = Employee.find(params[:id])
    @attendances = @employee.attendances.order('created_at DESC').page(params[:page]).per(MAX_DISPLAY_ATTENDANCE)
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:success] = 'ユーザー登録が完了しました'
      redirect_to employees_path
    else
      render 'new'
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      flash[:success] = '編集に成功しました'
      redirect_to @employee
    else
      render 'edit'
    end
  end

  def destroy
    Employee.find(params[:id]).destroy
    flash[:success] = 'ユーザーを削除しました'
    redirect_to employees_url
  end

  private

  def employee_params
    params.require(:employee).permit(:employee_id, :name, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    employee = Employee.find_by(employee_id: params[:session][:employee_id])
    if employee&.authenticate(params[:session][:password])
      log_in employee
      redirect_to employee, notice: 'ログインしました'
    else
      flash.now[:danger] = '従業員コード・パスワードが正しくないか登録されていません'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to employees_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # 属性がtrueのときのみ"◯"を表示する
  def display_circle(attr)
    if attr.present?
      return '◯'
    else
      return '×'
    end
  end

  # 時間を指定した方法で表示する
  def display_JPtime(time)
    if time.present?
      return time.strftime('%m/%d-%H:%M')
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(employee)
    session[:employee_id] = employee.id
  end

  # 渡されたユーザーをログアウトさせる
  def log_out
    session.delete(:employee_id)
    @current_employee = nil
  end

  # ログインしているユーザーがいる場合、@current_employeeにユーザーを代入する
  def current_employee
    if session[:employee_id]
      @current_employee ||= Employee.find_by(id: session[:employee_id])
    end
  end

  # ログインしているユーザーがいればtrue,いなければnilを返す
  def logged_in?
    !current_employee.nil?
  end
end

app/views/attendances/_attendance.html.erb
<li class="list-group-item">
  <span><%= attendance.created_at.strftime('%m/%d') %></span>
  <span>点数: <%= attendance.point %></span>
</li>

app/views/attendances/_form.html.erb
<%= form_with(model: attendance, local: true) do |f| %>
<%= render 'layouts/error_messages', object: f.object %>
  <div class="bg-light">
    <div class="form-group">
      <%= f.label :employee_id, '名前(必須)' %>
      <%= f.collection_select :employee_id, Employee.all, :id, :name, :prompt => true %>
    </div>
    <div class="form-group">
      <%= f.label :ride_at, '乗車時間' %>
      <%= f.datetime_select :ride_at, discard_year: true, use_month_numbers: true, selected: Date.today - 1, date_separator: '/', minute_step: 5 %>
    </div>
    <div class="form-group">
      <%= f.label :ride_in, '経路' %>
      <%= f.text_field :ride_in, placeholder:'(例) 東京駅 - 大手町', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :attr_one, '1 [挨拶]' %>
      <%= f.check_box :attr_one, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :attr_two, '2 [行き先の復唱、確認]' %>
      <%= f.check_box :attr_two, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :attr_three, '3 [発車時の後方目視確認及びドア閉めの確認]' %>
      <%= f.check_box :attr_three, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :attr_four, '4 [コースの確認]' %>
      <%= f.check_box :attr_four, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :attr_five, '5 [かしこまりました等の言葉遣い]' %>
      <%= f.check_box :attr_five, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :attr_six, '6 [社名、氏名の名乗り,シートベルトの声かけ]' %>
      <%= f.check_box :attr_six, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :attr_seven, '7 [会計時、料金の確認]' %>
      <%= f.check_box :attr_seven, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :attr_eight, '8 [適切な運転姿勢、服装]' %>
      <%= f.check_box :attr_eight, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :attr_nine, '9 [忘れ物注意の声がけ、確認]' %>
      <%= f.check_box :attr_nine, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :attr_ten, '10 [降車時の挨拶]' %>
      <%= f.check_box :attr_ten, class: 'form-control' %>
    </div>
    <div class="form-row">
      <div class="form-group col-md-9">
        <%= f.label :momo, '備考' %>
        <%= f.text_area :memo, placeholder: 'コメントを残すことができます', class: 'form-control' %>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :point, '点数(必須0~10)' %>
        <%= f.number_field :point, min: '0', max: '10', class: 'form-control' %>
      </div>
    </div>
    <%= f.submit 'チェック完了', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/attendances/index.html.erb
<nav aria-label="パンくずリスト">
  <ol class="breadcrumb mb-1">
    <li class="breadcrumb-item"><a>トップ</a></li>
    <li class="breadcrumb-item active" aria-current="page"><a>カメラチェック結果一覧</a></li>
  </ol>
</nav>
<nav class="navbar navbar-white bg-white">
  <span class="navbar-text"></span>
</nav>
<div class="container-fluid">
  <div>
    <% if @attendances.any? %>
      <div class="container-fluid">
        <%= paginate @attendances %>
        <div class="table-responsive">
          <table class="table table-striped table-md">
            <tr>
              <th>従業員ID</th>
              <th>名前</th>
              <th>経路</th>
              <th>項目1</th>
              <th>項目2</th>
              <th>項目3</th>
              <th>項目4</th>
              <th>項目5</th>
              <th>項目6</th>
              <th>項目7</th>
              <th>項目8</th>
              <th>項目9</th>
              <th>項目10</th>
              <th>点数</th>
              <th>作成時間</th>
            </tr>
            <% @attendances.each do |attendance| %>
            <tr>
              <td><%= attendance.employee.employee_id %></td>
              <td><%= link_to "#{attendance.employee.name}",employee_path(attendance.employee.id)  %></td>
              <td><%= attendance.ride_in %></td>
              <td><%= display_circle(attendance.attr_one) %></td>
              <td><%= display_circle(attendance.attr_two) %></td>
              <td><%= display_circle(attendance.attr_three) %></td>
              <td><%= display_circle(attendance.attr_four) %></td>
              <td><%= display_circle(attendance.attr_five) %></td>
              <td><%= display_circle(attendance.attr_six) %></td>
              <td><%= display_circle(attendance.attr_seven) %></td>
              <td><%= display_circle(attendance.attr_eight) %></td>
              <td><%= display_circle(attendance.attr_nine) %></td>
              <td><%= display_circle(attendance.attr_ten) %></td>
              <td><%= attendance.point %></td>
              <td><%= attendance.created_at.strftime('%m/%d-%H:%M') %></td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    <% else %>
      <%= "カメラチェックのデータがありません" %>
    <% end %>
  </div>
</div>

app/views/attendances/new.html.erb
<nav aria-label="パンくずリスト">
  <ol class="breadcrumb mb-1">
    <li class="breadcrumb-item"><a>トップ</a></li>
    <li class="breadcrumb-item active" aria-current="page">
      <a>カメラチェック - 従業員名とポイントは必ず入力する必要があります</a></li>
  </ol>
</nav>
<div class="container">
  <%= render 'form', attendance: @attendance %>
</div>

app/views/employees/_employee.html.erb
<li class="list-group-item">
  <%= link_to "#{employee.name}"+"  (従業員コード: #{employee.employee_id})", employee_path(employee.id) %>
  <!-- 管理者ユーザーのみに他のユーザーの削除リンクを表示する  -->
  <% if current_employee.admin? %>
    | <%= link_to "削除", employee, method: :delete, data: {confirm: "このユーザーを削除しますか"} %>
  <% end %>
</li>

app/views/employees/edit.html.erb
<nav aria-label="パンくずリスト">
  <ol class="breadcrumb mb-1">
    <li class="breadcrumb-item"><a>トップ</a></li>
    <li class="breadcrumb-item active" aria-current="page">
      <a>ユーザー情報編集</a></li>
  </ol>
</nav>
<div class="container">
  <%= form_with(model: @employee, local: true) do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :employee_id, '従業員コード' %>
    <%= f.number_field :employee_id, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワードの確認' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
    <%= f.submit '編集完了', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/employees/index.html.erb
<nav aria-label="パンくずリスト">
  <ol class="breadcrumb mb-1">
    <li class="breadcrumb-item"><a>トップ</a></li>
    <li class="breadcrumb-item active" aria-current="page"><a>ユーザー一覧</a></li>
  </ol>
</nav>
<div class="container">
  <nav class="navbar navbar-white bg-white">
    <span class="navbar-text">　</span>
    <div class="form-inline">
      <%= form_with url:'/employees', method: :get, local: true do |f| %>
        <%= f.text_field :name %>
        <%= f.submit('名前で検索') %>
      <% end %>
    </div>
  </nav>
</div>
<div class="container">
  <div>
    <% if @employees.any? %>
      <div class="container-fluid">
        <%= paginate @employees %>
        <div class="table-responsive">
          <table class="table table-striped table-md">
            <tr>
              <th>従業員ID</th>
              <th>名前</th>
              <!-- 管理者ユーザーのみに他のユーザーの削除リンクを表示する  -->
              <% if current_employee.admin? %>
                <th>ユーザーの削除</th>
              <% end %>
            </tr>
            <% @employees.each do |employee| %>
            <tr>
              <td><%= employee.employee_id %></td>
              <td><%= link_to "#{employee.name}",employee_path(employee.id)  %></td>
              <!-- 管理者ユーザーのみに他のユーザーの削除リンクを表示する  -->
              <td>
                <% if current_employee.admin? %>
                  <%= link_to "削除", employee, method: :delete, data: {confirm: "このユーザーを削除しますか"} %>
                <% end %>
              </td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    <% else %>
      <%= "該当するユーザーがいないか、データがありません" %>
    <% end %>
  </div>
</div>

app/views/employees/new.html.erb
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">新規登録</li>
    </ol>
  </nav>
  <%= form_with(model: @employee, local: true) do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :employee_id, '従業員コード' %>
    <%= f.number_field :employee_id, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワードの確認' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
    <%= f.submit '新規登録', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/employees/show.html.erb
<nav aria-label="パンくずリスト">
  <ol class="breadcrumb mb-1">
    <li class="breadcrumb-item"><a>トップ</a></li>
    <li class="breadcrumb-item">プロフィール</li>
    <li class="breadcrumb-item  active" aria-current="page">乗務員コード: <%= @employee.employee_id %></li>
    <li class="breadcrumb-item  active" aria-current="page">名前: <%= @employee.name %></li>
    <li class="breadcrumb-item  active" aria-current="page">管理者属性: <%= @employee.admin? %></li>
  </ol>
</nav>
<nav class="navbar navbar-white bg-white">
  <span class="navbar-text"></span>
</nav>
<div class="container-fluid">
  <div>
    <% if @employee.attendances.any? %>
      <div class="container-fluid">
        <%= paginate @attendances %>
        <div class="table-responsive">
          <table class="table table-striped table-md">
            <tr>
              <th>乗車時間</th>
              <th>経路</th>
              <th>項目1</th>
              <th>項目2</th>
              <th>項目3</th>
              <th>項目4</th>
              <th>項目5</th>
              <th>項目6</th>
              <th>項目7</th>
              <th>項目8</th>
              <th>項目9</th>
              <th>項目10</th>
              <th>点数</th>
              <th>作成時間</th>
            </tr>
            <% @attendances.each do |attendance| %>
            <tr>
              <td><%= display_JPtime(attendance.ride_at) %></td>
              <td><%= attendance.ride_in %></td>
              <td><%= display_circle(attendance.attr_one) %></td>
              <td><%= display_circle(attendance.attr_two) %></td>
              <td><%= display_circle(attendance.attr_three) %></td>
              <td><%= display_circle(attendance.attr_four) %></td>
              <td><%= display_circle(attendance.attr_five) %></td>
              <td><%= display_circle(attendance.attr_six) %></td>
              <td><%= display_circle(attendance.attr_seven) %></td>
              <td><%= display_circle(attendance.attr_eight) %></td>
              <td><%= display_circle(attendance.attr_nine) %></td>
              <td><%= display_circle(attendance.attr_ten) %></td>
              <td><%= attendance.point %></td>
              <td><%= display_JPtime(attendance.created_at) %></td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    <% else %>
      <%= "カメラチェックのデータがありません" %>
    <% end %>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger" role="alert">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-4 bg-white">
  <div class="container px-4">
    <span class="text-muted"></span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar sticky-top navbar-expand-md navbar-dark" style="background-color:midnightblue;">
  <a class="navbar-brand" href="/employees">Procuratio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbar">
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="nav-item active">
          <%= link_to "カメラチェック", new_attendance_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "カメラチェック結果一覧", attendances_path, class: "nav-link"  %>
        </li>
        <li class="nav-item active">
          <%= link_to "ユーザー一覧", employees_path, class: "nav-link"  %>
        </li>
        <ul class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <%= "#{current_employee.name}" %>
          </a>
          <div class="dropdown-menu">
            <%= link_to "プロフィール", current_employee, class: "dropdown-item"  %>
            <%= link_to "編集", edit_employee_path(current_employee), class: "dropdown-item"  %>
            <%= link_to "ログアウト", logout_path, method: :delete, class: "dropdown-item"  %>
          </div>
        </ul>
        <% else %>
        <li class="nav-item">
          <%= link_to "ログイン", login_path, class: "nav-link"  %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Procuratio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
    <!-- ロゴのフォント-->
    <style>
    	a{
    		font-family: 'Ubuntu', sans-serif;
    	}
    </style>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>